### ISSUE TITLE
 No longer working with Etherpad 1.8.13?

### ISSUE THREAD

**Issue by ldidry** [ether/ep_prompt_for_name#3]
I have this plugin installed on Etherpad 1.8.13 and as far as I can tell it's not doing anything.

**Comment by matthijskooijman** [comment]
Yup, same here. I do sometimes see some javascript errors in the console, but I also see those without this plugin installed, so I guess it's unrelated. Still, just in case:

> Uncaught ReferenceError: require is not defined
>    <anonymous> http://domain-redacted.tld/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=c7ac4813:1

**Comment by ycace** [comment]
It still not work on Etherpad-lite version 1.8.4😂

**Comment by JohnMcLear** [comment]
just tested in firefox on etherpad 1.8.15 and it's working

**Comment by ycace** [comment]
After clean cache it works now! thanks!👍🏻
